# Generated by Django 3.1.5 on 2021-01-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210111_0629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Park',
        ),
    ]
