# Generated by Django 3.1.5 on 2021-01-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210113_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={},
        ),
        migrations.AddField(
            model_name='park',
            name='starting_prices',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
