# Generated by Django 3.1.5 on 2021-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210113_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('flight', models.BooleanField()),
                ('accomodation', models.BooleanField()),
                ('pick_up', models.BooleanField()),
                ('tour_cars', models.BooleanField()),
            ],
        ),
    ]
