# Generated by Django 3.1.5 on 2021-02-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_park_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='starting_prices',
            new_name='accomodation',
        ),
        migrations.AddField(
            model_name='park',
            name='flight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='pickup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='tour_cars',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
