# Generated by Django 3.1.5 on 2021-01-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertracker',
            old_name='mikumi',
            new_name='visited_mikumi',
        ),
        migrations.RenameField(
            model_name='usertracker',
            old_name='ngorongoro',
            new_name='visited_ngorongoro',
        ),
        migrations.RenameField(
            model_name='usertracker',
            old_name='selou',
            new_name='visited_selou',
        ),
        migrations.RenameField(
            model_name='usertracker',
            old_name='serengeti',
            new_name='visited_serengeti',
        ),
    ]
