# Generated by Django 3.1.5 on 2021-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_admintracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintracker',
            options={},
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='place_1',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='place_2',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='place_3',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='place_4',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='place_5',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='place_6',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='place_7',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
    ]
