# Generated by Django 3.1.5 on 2021-02-16 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0006_auto_20210216_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertracker',
            name='tourist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
